-- CuTinsv1 Minified Script
local C=game:GetService("CoreGui")for _,g in pairs(C:GetChildren())do if g:IsA("ScreenGui")and g.Name:find("CuTins")then g:Destroy()end end
local G=Instance.new("ScreenGui")G.Name="CuTinsv1"G.Parent=C
local B=Instance.new("TextButton")B.Size=UDim2.new(0,50,0,50)B.Position=UDim2.new(0,20,0,20)B.BackgroundColor3=Color3.new(1,0,0)B.Text="🔥"B.TextColor3=Color3.new(1,1,1)B.TextSize=20,B.Font=Enum.Font.GothamBold,B.Active=true,B.Visible=true,B.Parent=G
local M=Instance.new("Frame")M.Size=UDim2.new(0,350,0,550)M.Position=UDim2.new(0.5,-175,0.5,-275)M.BackgroundColor3=Color3.new(0.1,0.1,0.2)M.BorderSizePixel=2,M.BorderColor3=Color3.new(1,1,0)M.Visible=true,M.Active=true,M.Draggable=true,M.Parent=G
local T=Instance.new("TextLabel")T.Size=UDim2.new(1,0,0,50)T.BackgroundColor3=Color3.new(1,0.2,0.2)T.Text="CuTinsv1"T.TextColor3=Color3.new(1,1,1)T.TextSize=18,T.Font=Enum.Font.GothamBold,T.Parent=M
local X=Instance.new("TextButton")X.Size=UDim2.new(0,40,0,40)X.Position=UDim2.new(1,-45,0,5)X.BackgroundColor3=Color3.new(1,0,0)X.Text="X"X.TextColor3=Color3.new(1,1,1)X.TextSize=18,X.Font=Enum.Font.GothamBold,X.Active=true,X.Parent=M
local S={Aimbot=false,ESP=false,TeamCheck=true,Speed=false,GodMode=false,Hitbox=false,HitboxSize=1.5,NoRecoil=false,InfAmmo=false}
local F={{"🎯 AIMBOT","Aimbot"},{"👁️ ESP","ESP"},{"🔵 TEAM CHECK","TeamCheck"},{"🏃 SPEED","Speed"},{"💀 GOD MODE","GodMode"},{"🎯 HITBOX","Hitbox"},{"🔫 NO RECOIL","NoRecoil"},{"∞ INF AMMO","InfAmmo"}}
local C=Instance.new("ScrollingFrame")C.Size=UDim2.new(1,-20,1,-70)C.Position=UDim2.new(0,10,0,60)C.BackgroundColor3=Color3.new(0.2,0.2,0.3)C.CanvasSize=UDim2.new(0,0,0,700)C.ScrollBarThickness=8,C.Parent=M
for i,f in pairs(F)do local b=Instance.new("TextButton")b.Size=UDim2.new(1,-10,0,50)b.Position=UDim2.new(0,5,0,(i-1)*55)b.BackgroundColor3=S[f[2]]and Color3.new(0,0.8,0)or Color3.new(0.3,0.3,0.4)b.Text=f[1].."\n"..(S[f[2]]and"🟢 ON"or"🔴 OFF")b.TextColor3=Color3.new(1,1,1)b.TextSize=14,b.Font=Enum.Font.GothamBold,b.TextWrapped=true,b.Active=true,b.Parent=C b.MouseButton1Click:Connect(function()S[f[2]]=not S[f[2]]b.BackgroundColor3=S[f[2]]and Color3.new(0,0.8,0)or Color3.new(0.3,0.3,0.4)b.Text=f[1].."\n"..(S[f[2]]and"🟢 ON"or"🔴 OFF")end)end
B.MouseButton1Click:Connect(function()M.Visible=not M.Visible end)X.MouseButton1Click:Connect(function()M.Visible=false end)
local P,R,L,U=game:GetService("Players"),game:GetService("RunService"),game.Players.LocalPlayer,game:GetService("UserInputService")
local I,A,O=U.TouchEnabled,not U.TouchEnabled,{}local m=L:GetMouse()local H=false
if A then m.Button1Down:Connect(function()if S.Aimbot then H=true end end)m.Button1Up:Connect(function()H=false end)else local S=Instance.new("TextButton")S.Size=UDim2.new(0,80,0,80)S.Position=UDim2.new(1,-90,0.5,-40)S.BackgroundColor3=Color3.new(0,1,0)S.Text="🔫\nBẮN"S.TextColor3=Color3.new(1,1,1)S.TextSize=14,S.Font=Enum.Font.GothamBold,S.TextWrapped=true,S.Visible=true,S.Active=true,S.Parent=G S.MouseButton1Down:Connect(function()if S.Aimbot then H=true S.BackgroundColor3=Color3.new(1,0,0)end end)S.MouseButton1Up:Connect(function()H=false S.BackgroundColor3=Color3.new(0,1,0)end)end
local E,N={},{}local function U()if not S.ESP then for p,h in pairs(E)do if h then h:Destroy()end end E={}return end for _,p in pairs(P:GetPlayers())do if p~=L and p.Character and p.Character:FindFirstChild("HumanoidRootPart")then local t=false if S.TeamCheck and p.Team and L.Team then t=(p.Team==L.Team)end if S.TeamCheck and t then if E[p]then E[p]:Destroy()E[p]=nil end continue end if not E[p]then local h=Instance.new("Highlight")h.Name="CuTinsESP"h.FillTransparency=0.9 h.OutlineTransparency=0 E[p]=h end local e=E[p]e.FillColor=Color3.new(1,0,0)e.OutlineColor=Color3.new(1,0.5,0.5)e.Adornee=p.Character e.Parent=p.Character else if E[p]then E[p]:Destroy()E[p]=nil end end end end
local function H()for _,p in pairs(P:GetPlayers())do if p~=L and p.Character then for _,b in pairs(p.Character:GetDescendants())do if b:IsA("BasePart")and(b.Name=="Head"or b.Name=="HumanoidRootPart"or b.Name:find("Torso"))then if S.Hitbox then if not N[b]then N[b]=b.Size end b.Size=N[b]*S.HitboxSize b.Transparency=0.3 b.CanCollide=false else if N[b]then b.Size=N[b]b.Transparency=0 end end end end end end end
R.Heartbeat:Connect(function()if H and L.Character then local t,c=nil,math.huge for _,p in pairs(P:GetPlayers())do if p~=L and p.Character then if S.TeamCheck and p.Team and L.Team then if p.Team==L.Team then continue end end local r=p.Character:FindFirstChild("HumanoidRootPart")if r then local d=(r.Position-L.Character.HumanoidRootPart.Position).Magnitude if d<c then c,d=t,p end end end end if t and t.Character then workspace.CurrentCamera.CFrame=CFrame.lookAt(workspace.CurrentCamera.CFrame.Position,t.Character.HumanoidRootPart.Position)end end U()H()if L.Character and L.Character:FindFirstChild("Humanoid")then L.Character.Humanoid.WalkSpeed=S.Speed and 40 or 16 end end)
local o=hookmetamethod(game,"__index",function(s,k)if not checkcaller()then if S.GodMode and tostring(s)=="Humanoid"and k=="Health"then return 100 end if S.NoRecoil and tostring(k):lower():find("recoil")then return 0 end if S.InfAmmo and tostring(k):lower():find("ammo")then return 999 end end return o(s,k)end)
print("✅ CuTinsv1 Loaded! "..(I and"MOBILE":"PC"))