-- CuTinsv1 Mobile Optimized
local C=game:GetService("CoreGui")for _,g in pairs(C:GetChildren())do if g:IsA("ScreenGui")then g:Destroy()end end
local G=Instance.new("ScreenGui")G.Name="CuTinsv1"G.Parent=C
local B=Instance.new("TextButton")B.Size=UDim2.new(0,60,0,60)B.Position=UDim2.new(0,20,0,20)B.BackgroundColor3=Color3.new(1,0,0)B.Text="🔥"B.TextColor3=Color3.new(1,1,1)B.TextSize=24,B.Active=true,B.Parent=G
local M=Instance.new("Frame")M.Size=UDim2.new(0,350,0,500)M.Position=UDim2.new(0.5,-175,0.5,-250)M.BackgroundColor3=Color3.new(0.1,0.1,0.2)M.BorderSizePixel=2,M.Visible=true,M.Active=true,M.Draggable=true,M.Parent=G
local T=Instance.new("TextLabel")T.Size=UDim2.new(1,0,0,50)T.BackgroundColor3=Color3.new(1,0.2,0.2)T.Text="CuTinsv1 MOBILE"T.TextColor3=Color3.new(1,1,1)T.TextSize=20,T.Parent=M
local X=Instance.new("TextButton")X.Size=UDim2.new(0,40,0,40)X.Position=UDim2.new(1,-45,0,5)X.BackgroundColor3=Color3.new(1,0,0)X.Text="X"X.TextColor3=Color3.new(1,1,1)X.Active=true,X.Parent=M
local S={Aimbot=false,ESP=false,TeamCheck=true,Speed=false,GodMode=false,Hitbox=false,HitboxSize=1.5}
local F={{"🎯 AIMBOT","Aimbot"},{"👁️ ESP","ESP"},{"🔵 TEAM CHECK","TeamCheck"},{"🏃 SPEED","Speed"},{"💀 GOD MODE","GodMode"},{"🎯 HITBOX","Hitbox"}}
local C=Instance.new("ScrollingFrame")C.Size=UDim2.new(1,-20,1,-70)C.Position=UDim2.new(0,10,0,60)C.BackgroundColor3=Color3.new(0.2,0.2,0.3)C.CanvasSize=UDim2.new(0,0,0,400)C.Parent=M
for i,f in pairs(F)do local b=Instance.new("TextButton")b.Size=UDim2.new(1,-10,0,60)b.Position=UDim2.new(0,5,0,(i-1)*65)b.BackgroundColor3=S[f[2]]and Color3.new(0,0.8,0)or Color3.new(0.3,0.3,0.4)b.Text=f[1].."\n"..(S[f[2]]and"ON":"OFF")b.TextColor3=Color3.new(1,1,1)b.TextSize=16,b.TextWrapped=true,b.Active=true,b.Parent=C b.MouseButton1Click:Connect(function()S[f[2]]=not S[f[2]]b.BackgroundColor3=S[f[2]]and Color3.new(0,0.8,0)or Color3.new(0.3,0.3,0.4)b.Text=f[1].."\n"..(S[f[2]]and"ON":"OFF")end)end
local SB=Instance.new("TextButton")SB.Size=UDim2.new(0,100,0,100)SB.Position=UDim2.new(1,-110,0.5,-50)SB.BackgroundColor3=Color3.new(0,1,0)SB.Text="🔫\nBẮN"SB.TextColor3=Color3.new(1,1,1)SB.TextSize=16,SB.TextWrapped=true,SB.Active=true,SB.Parent=G
B.MouseButton1Click:Connect(function()M.Visible=not M.Visible end)X.MouseButton1Click:Connect(function()M.Visible=false end)
local P,R,L,U=game:GetService("Players"),game:GetService("RunService"),game.Players.LocalPlayer,game:GetService("UserInputService")
local H=false SB.MouseButton1Down:Connect(function()if S.Aimbot then H=true SB.BackgroundColor3=Color3.new(1,0,0)end end)SB.MouseButton1Up:Connect(function()H=false SB.BackgroundColor3=Color3.new(0,1,0)end)
local E,N={},{}R.Heartbeat:Connect(function()if H and L.Character then local t,c=nil,9e9 for _,p in pairs(P:GetPlayers())do if p~=L and p.Character then if S.TeamCheck and p.Team and L.Team and p.Team==L.Team then continue end local r=p.Character:FindFirstChild("HumanoidRootPart")if r then local d=(r.Position-L.Character.HumanoidRootPart.Position).Magnitude if d<c then c,d=t,p end end end end if t and t.Character then workspace.CurrentCamera.CFrame=CFrame.lookAt(workspace.CurrentCamera.CFrame.Position,t.Character.HumanoidRootPart.Position)end end if not S.ESP then for p,h in pairs(E)do if h then h:Destroy()end end E={}else for _,p in pairs(P:GetPlayers())do if p~=L and p.Character and p.Character:FindFirstChild("HumanoidRootPart")then if S.TeamCheck and p.Team and L.Team and p.Team==L.Team then if E[p]then E[p]:Destroy()E[p]=nil end continue end if not E[p]then local h=Instance.new("Highlight")h.Name="ESP"h.FillTransparency=0.8 h.OutlineTransparency=0 h.FillColor=Color3.new(1,0,0)E[p]=h end E[p].Adornee=p.Character E[p].Parent=p.Character else if E[p]then E[p]:Destroy()E[p]=nil end end end end for _,p in pairs(P:GetPlayers())do if p~=L and p.Character then for _,b in pairs(p.Character:GetDescendants())do if b:IsA("BasePart")and(b.Name=="Head"or b.Name=="HumanoidRootPart")then if S.Hitbox then if not N[b]then N[b]=b.Size end b.Size=N[b]*S.HitboxSize b.Transparency=0.4 else if N[b]then b.Size=N[b]b.Transparency=0 end end end end end if L.Character and L.Character:FindFirstChild("Humanoid")then L.Character.Humanoid.WalkSpeed=S.Speed and 40 or 16 end end)hookmetamethod(game,"__index",function(s,k)if not checkcaller()and S.GodMode and tostring(s)=="Humanoid"and k=="Health"then return 100 end end)
print("✅ CuTinsv1 Mobile Ready! Nhấn nút đỏ 🔥 để mở menu, nút xanh 🔫 để aimbot")
